- name: check filebeat
  shell: "ss -tulnp src :{{ log.elastic.filebeat.http_port }} | grep {{ log.elastic.filebeat.http_port }}"
  ignore_errors: True
  register: filebeat_setup
  when: log.elastic.filebeat.install_check

- name: set_fact
  set_fact:
    filebeat_setup:
      rc: 1
  when: not log.elastic.filebeat.install_check

- name: install filebeat
  include_tasks: install.yaml
  when: filebeat_setup.rc != 0

- name: restart filebeat
  service:
    name: filebeat
    state: restarted
    enabled: True
  when: not log.elastic.filebeat.install_check
