- name: check nfs ntp installed
  shell: dpkg -l | grep ntp
  ignore_errors: True
  register: ntp_installed

- name: install ntp
  apt:
    name: ntp
    state: present
  when: ntp_installed.rc != 0

