- name: install redis
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm:
    chart_ref: "{{ __path }}{{ service.redis.chart.path }}"
    chart_repo_url: "{{ service.redis.chart.repo }}"
    chart_version: "{{ service.redis.chart.version }}"
    release_name: "{{ service.redis.name }}"
    release_namespace: "{{ service.namespace }}"
    create_namespace: yes
    atomic: yes
    release_values:
      image:
        registry: "{{ service.repository.strip('/') }}"
      auth:
        password: "{{ service.redis.password }}"
      master:
        resources:
          limits: "{{ service.redis.resources.limits }}"
          requests: "{{ service.redis.resources.requests }}"
        persistence:
          storageClass: "{{ service.storage_class }}"
          size: "{{ service.redis.resources.storage }}"
      replica:
        replicaCount: "{{ service.redis.replica.count }}"
        resources:
          limits: "{{ service.redis.resources.limits }}"
          requests: "{{ service.redis.resources.requests }}"
        persistence:
          storageClass: "{{ service.storage_class }}"
          size: "{{ service.redis.resources.storage }}"
