- name: set fact
  set_fact:
    __path: ""

- name: set fact
  set_fact:
    __path: "{{ chart.local_dir.rstrip('/') }}/"
  when: chart.local_dir.strip() != ""

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True

- name: template redis
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ service.redis.chart.path }}"
    chart_repo_url: "{{ service.redis.chart.repo }}"
    chart_version: "{{ service.redis.chart.version }}"
    release_values:
      image:
        registry: "{{ service.repository.strip('/') }}"
      auth:
        password: "{{ service.redis.password }}"
      master:
        resources:
          limits: "{{ service.redis.resources.limits }}"
          requests: "{{ service.redis.resources.requests }}"
        persistence:
          storageClass: "{{ service.storage_class }}"
          size: "{{ service.redis.resources.storage }}"
      replica:
        replicaCount: "{{ service.redis.replica.count }}"
        resources:
          limits: "{{ service.redis.resources.limits }}"
          requests: "{{ service.redis.resources.requests }}"
        persistence:
          storageClass: "{{ service.storage_class }}"
          size: "{{ service.redis.resources.storage }}"
  register: redis_template_result

- name: set facts
  set_fact:
    redis_template_stdout: "{{ redis_template_result.stdout_lines }}"

- name: get images
  set_fact:
    redis_images: "{{ redis_template_stdout | select('match', '.*image:.*') | list | regex_replace(' *image: *', '') | replace('\"', '')}}"
