- name: check node-exporter
  shell: "ss -tulnp src :{{ monitor.node_exporter.port }} | grep {{ monitor.node_exporter.port }}"
  ignore_errors: True
  register: node_exporter_setup
  when: monitor.node_exporter.install_check

- name: set_fact
  set_fact:
    node_exporter_setup:
      rc: 1
  when: not monitor.node_exporter.install_check

- name: install node-exporter
  include_tasks: install.yaml
  when: node_exporter_setup.rc != 0

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
    enabled: True
  when: not monitor.node_exporter.install_check
