calico_k8s:
 "3.21":
   k8s:
   - "1.17"
   - "1.18"
   - "1.19"
   - "1.20"
   - "1.21"
   - "1.22"
   - "1.23"
   images:
   - "{{ registry_prefix }}quay.io/tigera/operator:v1.23.3"
   - "{{ registry_prefix }}calico/node:v3.21.2"
   - "{{ registry_prefix }}calico/pod2daemon-flexvol:v3.21.2"
   - "{{ registry_prefix }}calico/cni:v3.21.2"
   - "{{ registry_prefix }}calico/typha:v3.21.2"
   - "{{ registry_prefix }}calico/kube-controllers:v3.21.2"
