- name: check nginx
  shell: docker ps -f name=nginx-lb | grep nginx
  register: nginx_installed
  ignore_errors: True

- name: create dir
  file:
    name: /etc/nginx-lb
    state: directory

- name: config nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx-lb/nginx.conf
  notify:
  - restart nginx

- name: flush handlers
  meta: flush_handlers

- block:
  - name: start nginx
    shell: "docker run --net=host --name nginx-lb -d -v /etc/nginx-lb/nginx.conf:/etc/nginx/nginx.conf --restart always {{ nginx.image }}"
  when: nginx_installed.rc != 0

- name: install keepalived
  include_role:
    name: keepalived
  when: inventory_hostname in groups["keepalived"]
