{{- if .Values.front.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-config
data:
{{- range $path, $config := .Values.front.config }}                                            
  {{ $path }}: |                                                                               
{{ $config | indent 6 -}}
{{- end -}}                                                                                    
{{- end -}}

