- name: check kube packages
  shell: kubelet --version
  ignore_errors: True
  register: kube_installed
- block:
  - name: install kubeadm kubelet kubectl
    apt:
      name: "{{ item }}={{ kubernetes.version }}-00"
      state: present
    with_items:
    - kubectl
    - kubelet
    - kubeadm
  when: kube_installed.rc != 0

- name: check nfs-client
  shell: showmount --version
  ignore_errors: True
  register: nfs_client_installed

- name: install nfs-client
  apt:
    name: nfs-common
    state: present
  when: nfs_client_installed.rc != 0

