- name: set fact
  set_fact:
    __path: ""
    __domain: "{{ ansible_host }}"

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True
  
- block:
  - name: copy charts
    copy:
      src: "{{ chart.local_dir.rstrip('/') }}/"
      dest: "/tmp/"
      force: true
  - name: set fact
    set_fact:
      __path: "/tmp/"
  when: chart.local_dir.strip() != ""

- name: set domain fact
  set_fact:
    __domain: "{{ service.kafka.domain }}"
  when: service.kafka.domain.strip() != ""

- name: setup kafka
  include_tasks: setup_kafka.yaml
