- name: set fact
  set_fact:
    __path: ""
    __domain: "{{ ansible_host }}"

- name: set fact
  set_fact:
    __path: "{{ chart.local_dir.rstrip('/') }}/"
  when: chart.local_dir.strip() != ""

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True

- name: set domain fact
  set_fact:
    __domain: "{{ service.kafka.domain }}"
  when: service.kafka.domain.strip() != ""

- name: template kafka
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ service.kafka.chart.path }}"
    chart_repo_url: "{{ service.kafka.chart.repo }}"
    chart_version: "{{ service.kafka.chart.version }}"
    release_values:
      zookeeper:
        image:
          registry: "{{ service.repository.strip('/') }}"
      image:
        registry: "{{ service.repository.strip('/') }}"
      replicaCount: "{{ service.kafka.replicas }}"
      externalAccess:
        service:
          type: NodePort
          domain: "{{ __domain }}"
          nodePort: "{{ service.kafka.node_ports }}"
  register: kafka_template_result

- name: set facts
  set_fact:
    kafka_template_stdout: "{{ kafka_template_result.stdout_lines }}"

- name: get images
  set_fact:
    kafka_images: "{{ kafka_template_stdout | select('match', '.*image:.*') | list | regex_replace(' *image: *', '') | replace('\"', '')}}"
