- name: create ns
  shell: kubectl create ns {{ log.namespace }}
  ignore_errors: True

- name: template config yaml
  template:
    src: config.yaml.j2
    dest: /tmp/log_elastalert_config.yaml

- name: apply config
  shell: "kubectl apply -f /tmp/log_elastalert_config.yaml -n {{ log.namespace }}"

- name: install elastAlert
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm:
    wait: yes
    wait_timeout: 10m0s
    chart_ref: "{{ __path }}{{ log.elastalert.chart.path }}"
    chart_repo_url: "{{ log.elastalert.chart.repo }}"
    chart_version: "{{ log.elastalert.chart.version }}"
    release_name: "{{ log.elastalert.name }}"
    release_namespace: "{{ log.namespace }}"
    create_namespace: yes
    atomic: yes
    release_values:
      image:
        repository: "{{ log.repository }}jertel/elastalert2"
      elasticsearch:
        host: "{{ log.elastalert.elasticsearch.host }}"
        port: "{{ log.elastalert.elasticsearch.port }}"
        username: "{{ log.elastalert.elasticsearch.username }}"
        password: "{{ log.elastalert.elasticsearch.password }}"
        verifyCerts: "False"
      rules: "{{ __rules }}"
      resources: "{{ log.elastalert.resources }}"
      writebackIndex: "{{ log.elastalert.writebackIndex }}"
      runIntervalMins: 1
      bufferTimeMins: 15
      args:
      - "--verbose"
      extraVolumes:
      - name: rules-global-config
        configMap:
          name: elastalert-rules-global-config
      extraVolumeMounts:
      - name: rules-global-config
        mountPath: /opt/elastalert/global.config
        subPath: global.config
