- name: set fact
  set_fact:
    __path: ""

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True

- block:
  - name: copy charts
    copy:
      src: "{{ chart.local_dir.rstrip('/') }}/"
      dest: "/tmp/"
      force: true
  - name: set fact
    set_fact:
      __path: "/tmp/"
  when: chart.local_dir.strip() != ""

- name: set fact
  set_fact:
    __argocd_hosts: []

- name: set __argocd_hosts fact
  set_fact:
    __argocd_hosts: "{{ __argocd_hosts + [(ingress.hosts['argocd']['host'] + '.' + item).strip('.')] }}"
  with_items: "{{ ingress.hosts['argocd']['domains'] }}"

- name: setup argocd
  include_tasks: setup.yaml
