- name: install ingress-nginx
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm:
    chart_ref: "{{ __path }}{{ basic.ingress_nginx.chart.path }}"
    chart_repo_url: "{{ basic.ingress_nginx.chart.repo }}"
    chart_version: "{{ basic.ingress_nginx.chart.version }}"
    release_name: "{{ basic.ingress_nginx.name }}"
    release_namespace: "{{ basic.namespace }}"
    create_namespace: yes
    atomic: yes
    release_values:
      controller:
        ingressClass: "{{ basic.ingress_nginx.config.ingress_class }}"
        kind: DaemonSet
        tolerations:
        - operator: "Exists"
        config:
          #ref: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-real-ip
          enable-real-ip: "true"
          #if true,redirect ssl to the specific port which is set with https-port
          use-port-in-redirects: "true"
        containerPort:
          http: "{{ basic.ingress_nginx.config.http_port }}"
          https: "{{ basic.ingress_nginx.config.https_port }}"
        extraArgs:
          "http-port": "{{ basic.ingress_nginx.config.http_port }}"
          "https-port": "{{ basic.ingress_nginx.config.https_port }}"
        image:
          registry: "{{ basic.repository }}k8s.gcr.io"
          digest: ""
        admissionWebhooks:
          patch:
            image:
              registry: "{{ basic.repository }}k8s.gcr.io"
              digest: ""
        hostNetwork: true
        service:
          enabled: false
          externalTrafficPolicy: Local
          type: NodePort
          nodePorts:
            http: "{{ basic.ingress_nginx.config.http_port }}"
            https: "{{ basic.ingress_nginx.config.https_port }}"
        metrics:
          enabled: true
      defaultBackend:
        enabled: true
        image:
          registry: "{{ basic.repository }}k8s.gcr.io"
