- name: set fact
  set_fact:
    __path: ""

- name: set fact
  set_fact:
    __path: "{{ chart.local_dir.rstrip('/') }}/"
  when: chart.local_dir.strip() != ""

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True

- name: template mysql
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ service.mysql.chart.path }}"
    chart_repo_url: "{{ service.mysql.chart.repo }}"
    chart_version: "{{ service.mysql.chart.version }}"
    release_values:
      image:
        registry: "{{ service.repository.strip('/') }}"
      auth:
        rootPassword: "{{ service.mysql.root_password }}"
      architecture: "{{ service.mysql.architecture }}"
      primary:
        resources:
          limits: "{{ service.mysql.resources.limits }}"
          requests: "{{ service.mysql.resources.requests }}"
        persistence:
          storageClass: "{{ service.storage_class }}"
          size: "{{ service.mysql.resources.storage }}"
      secondary:
        resources:
          limits: "{{ service.mysql.resources.limits }}"
          requests: "{{ service.mysql.resources.requests }}"
        persistence:
          storageClass: "{{ service.storage_class }}"
          size: "{{ service.mysql.resources.storage }}"
  register: mysql_template_result

- name: set facts
  set_fact:
    mysql_template_stdout: "{{ mysql_template_result.stdout_lines }}"

- name: get images
  set_fact:
    mysql_images: "{{ mysql_template_stdout | select('match', '.*image:.*') | list | regex_replace(' *image: *', '') | replace('\"', '')}}"
