- name: create workdir
  file:
   path: "{{ workdir }}"
   state: directory

- name: copy tidb chart
  copy:
    src: tidb
    dest: "{{ workdir }}"
    force: no

- name: install crd
  shell: kubectl apply -f crd.yaml
  args:
    chdir: "{{ workdir }}/tidb"

- name: install tidb-operator
  community.kubernetes.helm:
    chart_ref: "{{ workdir }}/tidb/tidb-operator"
    release_name: tidb-operator
    release_namespace: tidb-admin
    create_namespace: yes
    atomic: yes
    release_values:
      operatorImage: "{{ tidb.operator.image }}"
      scheduler:
        kubeSchedulerImageName: "{{ tidb.operator.scheduler_repository }}"

- name: set root password
  shell: "kubectl create ns tidb-aiops;kubectl create secret generic tidb-secret --from-literal=root={{ tidb.root_password }} -n tidb-aiops || echo ''"

- name: install tidb-cluster
  community.kubernetes.helm:
    chart_ref: "{{ workdir }}/tidb/tidb-cluster"
    release_name: tidb-cluster
    release_namespace: tidb-aiops
    create_namespace: yes
    atomic: yes
    release_values:
      discovery:
        image: "{{ tidb.discovery.image }}"
      pd:
        image: "{{ tidb.pd.image }}"
        storageClassName: "{{ tidb.pd.storage_class }}"
      tikv:
        image: "{{ tidb.tikv.image }}"
        storageClassName: "{{ tidb.tikv.storage_class }}"
      tidb:
        image: "{{ tidb.tidb.image }}"
        slowLogTailer:
          image: "{{ tidb.busybox.image }}"
        service:
          mysqlNodePort: 14000
      mysqlClient:
        image: "{{ tidb.mysql_client.image }}"
      busybox:
        image: "{{ tidb.busybox.image }}"
