download_packages:
  context: "centos-7"
  download_dir: "/tmp/download/"
  packages_list: []
  contexts:
    centos-7:
      image: "centos:7"
      package_manager: "yum"
    ubuntu-18.04:
      image: "ubuntu:18.04"
      package_manager: "apt"
