- name: set fact
  set_fact:
    __path: ""

- name: set fact
  set_fact:
    __path: "{{ chart.local_dir.rstrip('/') }}/"
  when: chart.local_dir.strip() != ""

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True

- name: include vars
  include_vars:
    dir: ../defaults

- name: template jenkins
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ devops.jenkins.chart.path }}"
    chart_repo_url: "{{ devops.jenkins.chart.repo }}"
    chart_version: "{{ devops.jenkins.chart.version }}"
    release_values:
      controller:
        image: "{{ devops.repository }}jenkins/jenkins"
        imagePullPolicy: "IfNotPresent"
        adminPassword: "{{ devops.jenkins.admin_password }}"
        resources:
          requests: "{{ devops.jenkins.resources.requests }}"
          limits: "{{ devops.jenkins.resources.limits }}"
        jenkinsUriPrefix: "{{ ingress.hosts['jenkins'].path }}"
        #install the latest plugins(you can speify the version, e.g. kubernetes:3734.v562b_b_a_627ea_c)
        installPlugins:
        - kubernetes
        - workflow-aggregator
        - git
        - configuration-as-code
        testEnabled: false
        sidecars:
          configAutoReload:
            image: "{{ devops.repository }}kiwigrid/k8s-sidecar:1.15.0"
      agent: "{{ __agent_config }}"
      persistence:
        enabled: true
        storageClass: "{{ devops.storage_class }}"
        size: "{{ devops.jenkins.resources.storage }}"
  register: jenkins_template_result

- name: set facts
  set_fact:
    jenkins_template_stdout: "{{ jenkins_template_result.stdout_lines }}"

- name: get images
  set_fact:
    jenkins_images: "{{ jenkins_template_stdout | select('match', '.*image:.*') | list | regex_replace(' *image: *', '') | replace('\"', '')}}"
