task_id: 2
workdir: "~/ansible_{{task_id}}"
tidb: 
  operator:
    image: docker.repo.local:5000/tidb-operator:v1.1.10
    scheduler_repository: docker.repo.local:5000/kube-scheduler
  discovery:
    image: docker.repo.local:5000/tidb-operator:v1.1.10
  pd: 
    image: docker.repo.local:5000/pd:v4.0.10
    storage_class: tidb-pd  
  tikv:
    image: docker.repo.local:5000/tikv:v4.0.10
    storage_class: tidb-tikv
  tidb:
    image: docker.repo.local:5000/tidb:v4.0.10
  busybox:
    image: docker.repo.local:5000/busybox:1.26.2
  mysql_client:
    image: docker.repo.local:5000/mysqlclient:v1.4.6
  root_password: cangoal
  node_port: 14000
