apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.url.system }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.url.clusterissuer }}
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.url.host }}
    http:
      paths:

      - path: /(.*)
        backend:
          serviceName: kangpaas-front
          servicePort: 80

      - path: /gate/(.*)
        backend:
          serviceName: kangpaas-gate
          servicePort: 8093
          
      - path: /data-cleaning/(.*)
        backend:
          serviceName: data-cleaning
          servicePort: 80

      - path: /contract/(.*)
        backend:
          serviceName: contract-managent
          servicePort: 8082

      - backend:
          serviceName: message-management
          servicePort: 8084
        path: /message-mgnt/(.*)

  tls:
  - hosts:
    - {{ .Values.url.host }}
    secretName: "{{ .Values.url.host }}-ingress"
