- name: check docker-ce
  shell: docker --version
  ignore_errors: True
  register: docker_installed
- block:
  - name: get version
    shell: "apt list -a docker-ce | awk '{print $2}' | grep {{ docker.version }}"
    register: result
  - name: install docker-ce
    apt:
      name: "docker-ce={{ result.stdout }}"
      state: present
  - name: stop docker-ce
    service:
      name: docker
      state: stopped
  when: docker_installed.rc != 0
