- name: install docker on debian
  include_tasks: debian.yaml
  when: ansible_distribution_file_variety == "Debian"

- name: install docker on redhat
  include_tasks: redhat.yaml
  when: ansible_distribution_file_variety == "RedHat"

- name: create dir
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: directory
  with_items:
  - containerd.service.d
  - docker.service.d

- name: copy containerd daemon proxy
  template:
    src: proxy.conf.j2
    dest: /etc/systemd/system/containerd.service.d/proxy.conf
  notify: restart containerd

- name: copy docker daemon proxy
  template:
    src: proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/proxy.conf
  notify: restart docker

- name: systemd reload
  systemd:
    daemon_reload: True

- name: create dir
  file:
    path: "/etc/{{ item }}"
    state: directory
  with_items:
  - containerd
  - docker

- name: config containerd
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  notify:
  - "restart containerd"

- name: flush handlers
  meta: flush_handlers
  
- name: config docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
  - "restart docker"

- name: flush handlers
  meta: flush_handlers

# - name: start docker
#   service:
#     name: docker
#     state: started
#
# - name: reload docker
#   service:
#     name: docker
#     state: reloaded
#     enabled: True

- name: set sysctl
  sysctl:
    name: "{{ item }}"
    value: '1'
  with_items:
  - "net.ipv4.ip_forward"
  - "net.bridge.bridge-nf-call-iptables"
  - "net.bridge.bridge-nf-call-ip6tables"
