- name: set fact
  set_fact:
    __path: ""

- name: set fact
  set_fact:
    __path: "{{ chart.local_dir.rstrip('/') }}/"
  when: chart.local_dir.strip() != ""

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True

- name: template elasticsearch
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ log.elastic.elasticsearch.chart.path }}"
    chart_repo_url: "{{ log.elastic.elasticsearch.chart.repo }}"
    chart_version: "{{ log.elastic.version }}"
    release_values:
      image: "{{ log.repository }}docker.elastic.co/elasticsearch/elasticsearch"
      resources:
        requests: "{{ log.elastic.elasticsearch.resources.requests }}"
        limits: "{{ log.elastic.elasticsearch.resources.limits }}"
      volumeClaimTemplate:
        resources:
          requests:
            storage: "{{ log.elastic.elasticsearch.resources.storage }}"
      esJavaOpts: "{{ log.elastic.elasticsearch.resources.esJavaOpts }}"
  register: es_template_result

- name: template kibana
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ log.elastic.kibana.chart.path }}"
    chart_repo_url: "{{ log.elastic.kibana.chart.repo }}"
    chart_version: "{{ log.elastic.version }}"
    release_values:
      image: "{{ log.repository }}docker.elastic.co/kibana/kibana"
      healthCheckPath: "/kibana/app/kibana"
      kibanaConfig:
        kibana.yml: |
          server:
            basePath: /kibana
            rewriteBasePath: true
  register: kibana_template_result

- name: template logstash
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ log.elastic.logstash.chart.path }}"
    chart_repo_url: "{{ log.elastic.logstash.chart.repo }}"
    chart_version: "{{ log.elastic.version }}"
    release_values:
      image: "{{ log.repository }}docker.elastic.co/logstash/logstash"
      replicas: "{{ log.elastic.logstash.replicas }}"
      resources:
        requests: "{{ log.elastic.logstash.resources.requests }}"
        limits: "{{ log.elastic.logstash.resources.limits }}"
      logstashJavaOpts: "{{ log.elastic.logstash.resources.logstashJavaOpts }}"
  register: logstash_template_result

- name: template filebeat
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ log.elastic.filebeat.chart.path }}"
    chart_repo_url: "{{ log.elastic.filebeat.chart.repo }}"
    chart_version: "{{ log.elastic.version }}"
    release_values:
      image: "{{ log.repository }}docker.elastic.co/beats/filebeat"
  register: filebeat_template_result

- name: set facts
  set_fact:
    elastic_init_images:
    - "{{ log.repository }}curlimages/curl:7.73.0"
- name: set facts
  set_fact:
    elastic_template_stdout: "{{ es_template_result.stdout_lines + kibana_template_result.stdout_lines + logstash_template_result.stdout_lines + filebeat_template_result.stdout_lines + elastic_init_images }}"

- name: get images
  set_fact:
    elastic_images: "{{ elastic_template_stdout | select('match', '.*image:.*') | list | regex_replace(' *image: *', '') | replace('\"', '')}}"

- name: set facts
  set_fact:
    elastic_images: "{{ elastic_images + elastic_init_images }}"
