- name: check registry
  shell: ss -tulnp src :5000 | grep 5000
  ignore_errors: True
  register: registry_installed

- block:

  - name: pull image
    shell: docker pull registry:2

  - name: start registry
    shell: docker run -d -p 5000:5000 --name registry -v /var/lib/docker-registry/:/var/lib/registry --restart always registry:2
  when: registry_installed.rc != 0
