- name: install cert-manager
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm:
    chart_ref: "{{ __path }}{{ basic.cert_manager.chart.path }}"
    chart_repo_url: "{{ basic.cert_manager.chart.repo }}"
    chart_version: "{{ basic.cert_manager.chart.version }}"
    release_name: "{{ basic.cert_manager.name }}"
    release_namespace: "{{ basic.namespace }}"
    create_namespace: yes
    atomic: yes
    release_values:
      installCRDs: true
      image:
        repository: "{{ basic.repository }}quay.io/jetstack/cert-manager-controller"
      cainjector:
        image:
          repository: "{{ basic.repository }}quay.io/jetstack/cert-manager-cainjector"
      startupapicheck:
        image:
          repository: "{{ basic.repository }}quay.io/jetstack/cert-manager-ctl"
      webhook:
        image:
          repository: "{{ basic.repository }}quay.io/jetstack/cert-manager-webhook"
