- name: set fact
  set_fact:
    __path: ""

- name: set fact
  set_fact:
    __path: "{{ chart.local_dir.rstrip('/') }}/"
  when: chart.local_dir.strip() != ""

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True

- name: template cert-manager
  environment: "{{ __proxy_env | default(omit) }}"
  kubernetes.core.helm_template:
    chart_ref: "{{ __path }}{{ basic.cert_manager.chart.path }}"
    chart_repo_url: "{{ basic.cert_manager.chart.repo }}"
    chart_version: "{{ basic.cert_manager.chart.version }}"
    release_values:
      image:
        repository: "{{ basic.repository }}quay.io/jetstack/cert-manager-controller"
      cainjector:
        image:
          repository: "{{ basic.repository }}quay.io/jetstack/cert-manager-cainjector"
      startupapicheck:
        image:
          repository: "{{ basic.repository }}quay.io/jetstack/cert-manager-ctl"
      webhook:
        image:
          repository: "{{ basic.repository }}quay.io/jetstack/cert-manager-webhook"
  register: certmanager_template_result

- name: set facts
  set_fact:
    certmanager_template_stdout: "{{ certmanager_template_result.stdout_lines }}"

- name: get images
  set_fact:
    certmanager_images: "{{ certmanager_template_stdout | select('match', '.*image:.*') | list | regex_replace(' *image: *', '') | replace('\"', '')}}"
