apiVersion: v1
kind: ConfigMap
metadata:
  name: contract
data:
  dbConnection.ini: |
    [DEFAULT]
    HOSTNAME = {{ .Values.mysql.ip }}
    PORT = {{ .Values.mysql.port }}
    DATABASE = {{ .Values.mysql.db_name }}
    USERNAME = {{ .Values.mysql.username }}
    PASSWORD = {{ .Values.mysql.password }}
  settings.yaml: |
    kafka_address: "{{ .Values.kafka.host }}:{{ .Values.kafka.port}}"
    kafka_topic: topic_message
    kafka_group: messagetest
  foreign_url.ini: |
    [DEFAULT]
    GET_USER_URL = http://kangpaas-systemmgnt:8095/api/v1/security/staff/
    GET_USER_LIST_URL = http://kangpaas-systemmgnt:8095/api/v1/security/staff/query
    POST_REQUEST_HEADERS = {"content-type": "application/json"}
    COMPANY_URL = http://kangpaas-systemmgnt:8095/api/v1/security/company/
    GET_COMPANY_LIST_URL = http://kangpaas-systemmgnt:8095/api/v1/security/company/query
    HEADERS = {"content-type": "application/json"}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-mgnt
data:
  dbConnection.ini: |
    [DEFAULT]
    HOSTNAME = {{ .Values.mysql.ip }}
    PORT = {{ .Values.mysql.port }}
    DATABASE = {{ .Values.mysql.db_name }}
    USERNAME = {{ .Values.mysql.username }}
    PASSWORD = {{ .Values.mysql.password }}
  settings.yaml: |
    kafka_address: {{ .Values.kafka.host }}:{{ .Values.kafka.port}}
    kafka_topic: topic_message
    kafka_group: messagetest
  foreign_url.ini: |
    [DEFAULT]
    SendToAssignUser_URL = http://kangpaas-websocket:8078/api/v1/ws/sendToAssignUser
    POST_REQUEST_HEADERS = {"content-type": "application/json"}
    GETAuth_URL = http://kangpaas-systemmgnt:8095/api/v1/security/user/auth/all

