- hosts: work_master
  gather_facts: True
  become: True
  roles:
  - { role: jaeger , when: "service_mesh.jaeger.enabled" }
  - { role: opentelemetry , when: "service_mesh.opentelemetry.enabled" }
  - { role: istio , when: "service_mesh.istio.enabled" }
