- hosts: all
  gather_facts: True
  become: True
  roles:
  - { role: elastic, when: "inventory_hostname in groups['work_master']" }
  - { role: elastalert, when: "inventory_hostname in groups['work_master']" }

- hosts: all:!monitor_exceptions
  gather_facts: True
  become: True
  roles:
  - filebeat
