- hosts: node-3
  gather_facts: True
  become: True
  tasks:
  - name: get kubelet version
    shell:  "apt list -a kubelet | awk '{print $2}' | grep {{ kubernetes.version }}"
    register: result
  - name: install kubelet
    apt:
      name: "kubelet={{ result.stdout }}"
      state: present
  - name: get kubeadm version
    shell:  "apt list -a kubeadm | awk '{print $2}' | grep {{ kubernetes.version }}"
    register: result
  - name: install kubeadm
    apt:
      name: "kubeadm={{ result.stdout }}"
      state: present
  - name: get kubectl version
    shell:  "apt list -a kubectl | awk '{print $2}' | grep {{ kubernetes.version }}"
    register: result
  - name: install kubectl
    apt:
      name: "kubectl={{ result.stdout }}"
      state: present
